name: Run Docker and Swagger UI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker container
        run: |
          cd part1
          docker build -t my-docker-image .
          docker run my-docker-image

  swagger_job:
    runs-on: ubuntu-latest
    needs: docker_job  # swagger_job зависит от выполнения docker_job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Swagger UI script
        run: |
          cd part2
          chmod +x run_swagger.sh
          ./run_swagger.sh
