name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Part1
        run: |
          cd Part1
          docker build -t my-docker-image .
          # Запускаем контейнер в фоновом режиме
          docker run -d --name my-container my-docker-image
          sleep 10  # Даем время на запуск сервера
          echo "Сервер Part1 запущен"

      - name: Stop Part1
        run: |
          docker stop my-container
          docker rm my-container
          echo "Сервер Part1 остановлен"

      - name: Run Swagger in Part2
        run: |
          cd Part2
          chmod +x run_swagger.sh
          # Запускаем скрипт в фоновом режиме
          ./run_swagger.sh &
          SWAGGER_PID=$!
          echo "Сервер Part2 запущен"

          # Даем время послушать сервер
          sleep 10

          # Завершаем скрипт
          kill $SWAGGER_PID || true  # Не обращаем внимания на ошибку, если PID не существует
          wait $SWAGGER_PID || true   # Ждем завершения (если это возможно)
          echo "Сервер Part2 остановлен"
